CREATE TABLE IF NOT EXISTS Author(id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS Genre(id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS Comment(id BIGINT AUTO_INCREMENT PRIMARY KEY, comment VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS Book(id BIGINT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, author_id BIGINT, genre_id BIGINT, comment_id BIGINT, FOREIGN KEY (author_id) REFERENCES Author(id), FOREIGN KEY (genre_id) REFERENCES Genre(id), FOREIGN KEY (comment_id) REFERENCES Comment(id));



